<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 4 - Andrea

This document aims to organise the commercial verbal and visual subcorpora data for Canonical Correlation Analysis (CCA).

## Commercial Verbal Subcorpus

Define the project name.

In [1]:
PROJECT = "cl_st1_ph2_andrea"

In [2]:
from pathlib import Path

SCORES_FILE = Path(f"../{PROJECT}/sas/output_{PROJECT}/{PROJECT}_scores_only.tsv")
FILE_IDS_PATH = Path(f"../{PROJECT}/file_ids.txt")

### Load factor scores

In [3]:
import pandas as pd

scores_verbal_df = pd.read_csv(SCORES_FILE, sep="\t")
scores_verbal_df = scores_verbal_df.rename(columns={"filename": "file_id"})

scores_verbal_df

,file_id,decade,group,fac1,fac2,fac3,fac4,fac5,fac6,fac7,...,v000256,v000257,v000258,v000259,v000260,v000261,v000262,v000263,v000264,v000265
0,t000001,1950,1950,1,-1,0,-3,0,1,2,...,0,0,0,0,0,0,0,0,0,0
1,t000002,1950,1950,8,0,3,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,t000003,1950,1950,4,1,-1,-8,-1,0,2,...,0,0,0,1,0,0,0,0,0,0
3,t000004,1950,1950,2,1,-1,-1,1,-6,-1,...,0,0,0,0,0,0,1,0,0,0
4,t000005,1950,1950,3,-1,1,-1,-1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,t000820,2020,2020,2,1,1,0,0,-1,0,...,0,0,0,0,0,0,0,0,0,0
816,t000821,2020,2020,-1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
817,t000822,2020,2020,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
818,t000823,2020,2020,2,0,1,1,-1,0,0,...,0,0,0,0,0,0,0,0,0,1
819,t000824,2020,2020,1,0,0,0,-1,-1,0,...,0,0,0,0,0,1,1,0,0,0

### Load file ID mapping

In [4]:
file_ids_verbal_df = pd.read_csv(
    FILE_IDS_PATH,
    sep=" ",
    names=["file_id", "group_filename"],
)

file_ids_verbal_df.head()

   file_id          group_filename
0  t000001  1950/tv_com_1950_1.txt
1  t000002  1950/tv_com_1950_3.txt
2  t000003  1950/tv_com_1950_5.txt
3  t000004  1950/tv_com_1950_6.txt
4  t000005  1950/tv_com_1950_7.txt

### Merge factor scores with file ID mapping

In [5]:
scores_file_ids_verbal_df = scores_verbal_df.merge(file_ids_verbal_df, on="file_id", how="left")
scores_file_ids_verbal_df = scores_file_ids_verbal_df[
    ["file_id", "group_filename"]
    + [col for col in scores_file_ids_verbal_df.columns if col not in ["file_id", "group_filename"]]
    ]

scores_file_ids_verbal_df

,file_id,group_filename,decade,group,fac1,fac2,fac3,fac4,fac5,fac6,...,v000256,v000257,v000258,v000259,v000260,v000261,v000262,v000263,v000264,v000265
0,t000001,1950/tv_com_1950_1.txt,1950,1950,1,-1,0,-3,0,1,...,0,0,0,0,0,0,0,0,0,0
1,t000002,1950/tv_com_1950_3.txt,1950,1950,8,0,3,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,t000003,1950/tv_com_1950_5.txt,1950,1950,4,1,-1,-8,-1,0,...,0,0,0,1,0,0,0,0,0,0
3,t000004,1950/tv_com_1950_6.txt,1950,1950,2,1,-1,-1,1,-6,...,0,0,0,0,0,0,1,0,0,0
4,t000005,1950/tv_com_1950_7.txt,1950,1950,3,-1,1,-1,-1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,t000820,2020/tv_com_2020_114.txt,2020,2020,2,1,1,0,0,-1,...,0,0,0,0,0,0,0,0,0,0
816,t000821,2020/tv_com_2020_115.txt,2020,2020,-1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
817,t000822,2020/tv_com_2020_116.txt,2020,2020,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
818,t000823,2020/tv_com_2020_118.txt,2020,2020,2,0,1,1,-1,0,...,0,0,0,0,0,0,0,0,0,1
819,t000824,2020/tv_com_2020_119.txt,2020,2020,1,0,0,0,-1,-1,...,0,0,0,0,0,1,1,0,0,0

### Prepare verbal factor-score columns for CCA

Rename the verbal factor-score columns from `fac<n>` to `ver<n>` and keep only the file identifiers, decade metadata, and renamed verbal score columns needed for Canonical Correlation Analysis.

In [6]:
import re

verbal_factor_cols = [col for col in scores_file_ids_verbal_df.columns if re.fullmatch(r"fac\d+", col)]
verbal_factor_cols = sorted(verbal_factor_cols, key=lambda col: int(col.replace("fac", "")))

verbal_rename_map = {
    col: col.replace("fac", "ver")
    for col in verbal_factor_cols
}

scores_file_ids_verbal_df = scores_file_ids_verbal_df.rename(columns=verbal_rename_map)

verbal_cols = [verbal_rename_map[col] for col in verbal_factor_cols]

scores_file_ids_verbal_df = scores_file_ids_verbal_df[
    ["file_id", "group_filename", "decade"] + verbal_cols
    ]

scores_file_ids_verbal_df

,file_id,group_filename,decade,ver1,ver2,ver3,ver4,ver5,ver6,ver7,ver8
0,t000001,1950/tv_com_1950_1.txt,1950,1,-1,0,-3,0,1,2,2
1,t000002,1950/tv_com_1950_3.txt,1950,8,0,3,1,1,1,0,2
2,t000003,1950/tv_com_1950_5.txt,1950,4,1,-1,-8,-1,0,2,0
3,t000004,1950/tv_com_1950_6.txt,1950,2,1,-1,-1,1,-6,-1,1
4,t000005,1950/tv_com_1950_7.txt,1950,3,-1,1,-1,-1,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...
815,t000820,2020/tv_com_2020_114.txt,2020,2,1,1,0,0,-1,0,0
816,t000821,2020/tv_com_2020_115.txt,2020,-1,0,0,0,0,0,0,0
817,t000822,2020/tv_com_2020_116.txt,2020,0,0,0,0,0,0,0,0
818,t000823,2020/tv_com_2020_118.txt,2020,2,0,1,1,-1,0,0,1
819,t000824,2020/tv_com_2020_119.txt,2020,1,0,0,0,-1,-1,0,0

## Commercial Visual Subcorpus

Define the project name.

In [7]:
PROJECT = "cl_st1_ph3_andrea"

In [8]:
from pathlib import Path

SCORES_FILE = Path(f"../{PROJECT}/sas/output_{PROJECT}/{PROJECT}_scores_only.tsv")
FILE_IDS_PATH = Path(f"../{PROJECT}/file_ids.txt")

### Load factor scores

In [9]:
import pandas as pd

scores_visual_df = pd.read_csv(SCORES_FILE, sep="\t")
scores_visual_df = scores_visual_df.rename(columns={"filename": "file_id"})

scores_visual_df

,file_id,decade,group,fac1,fac2,fac3,fac4,fac5,fac6,fac7,...,v000679,v000680,v000681,v000682,v000683,v000684,v000685,v000686,v000687,v000688
0,t000001,1950,1950,1,0,1,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
1,t000002,1950,1950,0,8,0,2,2,3,2,...,0,0,0,0,0,0,0,0,0,0
2,t000003,1950,1950,1,0,2,0,2,0,5,...,0,0,0,0,0,0,0,0,0,0
3,t000004,1950,1950,2,-1,3,1,3,0,3,...,0,0,0,0,0,0,0,0,0,1
4,t000005,1950,1950,1,0,0,3,0,0,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819,t000820,2020,2020,5,17,3,4,8,2,2,...,0,0,0,0,0,0,0,0,0,0
820,t000821,2020,2020,2,8,8,3,7,1,-4,...,0,0,0,0,0,0,0,0,0,0
821,t000822,2020,2020,8,9,1,2,8,3,1,...,0,1,0,0,0,0,0,0,1,1
822,t000823,2020,2020,13,3,0,3,0,0,1,...,0,0,0,0,0,0,0,0,0,0
823,t000824,2020,2020,9,7,2,-3,5,3,2,...,0,1,0,0,0,0,0,0,1,0

### Load file ID mapping

In [10]:
file_ids_visual_df = pd.read_csv(
    FILE_IDS_PATH,
    sep=" ",
    names=["file_id", "group_filename"],
)

file_ids_visual_df.head()

   file_id          group_filename
0  t000001  1950/tv_com_1950_1.txt
1  t000002  1950/tv_com_1950_3.txt
2  t000003  1950/tv_com_1950_5.txt
3  t000004  1950/tv_com_1950_6.txt
4  t000005  1950/tv_com_1950_7.txt

### Merge factor scores with file ID mapping

In [11]:
scores_file_ids_visual_df = scores_visual_df.merge(file_ids_visual_df, on="file_id", how="left")
scores_file_ids_visual_df = scores_file_ids_visual_df[
    ["file_id", "group_filename"]
    + [col for col in scores_file_ids_visual_df.columns if col not in ["file_id", "group_filename"]]
    ]

scores_file_ids_visual_df

,file_id,group_filename,decade,group,fac1,fac2,fac3,fac4,fac5,fac6,...,v000679,v000680,v000681,v000682,v000683,v000684,v000685,v000686,v000687,v000688
0,t000001,1950/tv_com_1950_1.txt,1950,1950,1,0,1,1,2,1,...,0,0,0,0,0,0,0,0,0,0
1,t000002,1950/tv_com_1950_3.txt,1950,1950,0,8,0,2,2,3,...,0,0,0,0,0,0,0,0,0,0
2,t000003,1950/tv_com_1950_5.txt,1950,1950,1,0,2,0,2,0,...,0,0,0,0,0,0,0,0,0,0
3,t000004,1950/tv_com_1950_6.txt,1950,1950,2,-1,3,1,3,0,...,0,0,0,0,0,0,0,0,0,1
4,t000005,1950/tv_com_1950_7.txt,1950,1950,1,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
819,t000820,2020/tv_com_2020_114.txt,2020,2020,5,17,3,4,8,2,...,0,0,0,0,0,0,0,0,0,0
820,t000821,2020/tv_com_2020_115.txt,2020,2020,2,8,8,3,7,1,...,0,0,0,0,0,0,0,0,0,0
821,t000822,2020/tv_com_2020_116.txt,2020,2020,8,9,1,2,8,3,...,0,1,0,0,0,0,0,0,1,1
822,t000823,2020/tv_com_2020_118.txt,2020,2020,13,3,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
823,t000824,2020/tv_com_2020_119.txt,2020,2020,9,7,2,-3,5,3,...,0,1,0,0,0,0,0,0,1,0

### Prepare visual factor-score columns for CCA

Rename the visual factor-score columns from `fac<n>` to `ver<n>` and keep only the file identifiers, decade metadata, and renamed visual score columns needed for Canonical Correlation Analysis.

In [12]:
import re

verbal_factor_cols = [col for col in scores_file_ids_visual_df.columns if re.fullmatch(r"fac\d+", col)]
verbal_factor_cols = sorted(verbal_factor_cols, key=lambda col: int(col.replace("fac", "")))

verbal_rename_map = {
    col: col.replace("fac", "vis")
    for col in verbal_factor_cols
}

scores_file_ids_visual_df = scores_file_ids_visual_df.rename(columns=verbal_rename_map)

verbal_cols = [verbal_rename_map[col] for col in verbal_factor_cols]

scores_file_ids_visual_df = scores_file_ids_visual_df[
    ["file_id", "group_filename", "decade"] + verbal_cols
    ]

scores_file_ids_visual_df

,file_id,group_filename,decade,vis1,vis2,vis3,vis4,vis5,vis6,vis7,vis8
0,t000001,1950/tv_com_1950_1.txt,1950,1,0,1,1,2,1,1,1
1,t000002,1950/tv_com_1950_3.txt,1950,0,8,0,2,2,3,2,-1
2,t000003,1950/tv_com_1950_5.txt,1950,1,0,2,0,2,0,5,0
3,t000004,1950/tv_com_1950_6.txt,1950,2,-1,3,1,3,0,3,0
4,t000005,1950/tv_com_1950_7.txt,1950,1,0,0,3,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...
819,t000820,2020/tv_com_2020_114.txt,2020,5,17,3,4,8,2,2,3
820,t000821,2020/tv_com_2020_115.txt,2020,2,8,8,3,7,1,-4,0
821,t000822,2020/tv_com_2020_116.txt,2020,8,9,1,2,8,3,1,10
822,t000823,2020/tv_com_2020_118.txt,2020,13,3,0,3,0,0,1,0
823,t000824,2020/tv_com_2020_119.txt,2020,9,7,2,-3,5,3,2,-3

## Identify misalignment between visual and verbal dimension score DataFrames

In [14]:
verbal_file_ids = set(scores_file_ids_verbal_df["file_id"])
visual_file_ids = set(scores_file_ids_visual_df["file_id"])

file_id_diff = {
    "only_in_verbal": sorted(verbal_file_ids - visual_file_ids),
    "only_in_visual": sorted(visual_file_ids - verbal_file_ids),
    "n_only_in_verbal": len(verbal_file_ids - visual_file_ids),
    "n_only_in_visual": len(visual_file_ids - verbal_file_ids),
    "n_in_both": len(verbal_file_ids & visual_file_ids),
    "n_verbal": len(verbal_file_ids),
    "n_visual": len(visual_file_ids),
}

display(file_id_diff)

{'only_in_verbal': [],
 'only_in_visual': ['t000455', 't000474', 't000481', 't000538'],
 'n_only_in_verbal': 0,
 'n_only_in_visual': 4,
 'n_in_both': 820,
 'n_verbal': 820,
 'n_visual': 824}

### Save selected commercials metadata as NDJSON, Excel, and TSV

In [3]:
tv_commercials_selected_1_df.to_json(
    "corpus/00_sources/tv_commercials_selected_1.ndjson",
    orient="records",
    lines=True,
    force_ascii=False
)

tv_commercials_selected_1_df.to_excel(
    "corpus/00_sources/tv_commercials_selected_1.xlsx",
    index=False,
    engine="openpyxl"
)

tv_commercials_selected_1_df.to_csv(
    "corpus/00_sources/tv_commercials_selected_1.tsv",
    sep="\t",
    index=False
)