<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 1 - Andrea

This document aims to organise the data collection and sampling for this project.

## Data Collection

### Import `TV_commercials_1950_2025.xlsx` into a pandas DataFrame

In [1]:
import pandas as pd

tv_commercials_df = pd.read_excel(
    "corpus/00_sources/TV_commercials_1950_2025.xlsx",
    engine="openpyxl"
)

In [3]:
tv_commercials_df = tv_commercials_df.drop(columns=["Unnamed: 7", "Unnamed: 8"])

### Add sequential video identifiers

In [5]:
unique_video_ids = {
    url: f"video_{index:04d}"
    for index, url in enumerate(tv_commercials_df["URL"].drop_duplicates(), start=1)
}

video_id_position = tv_commercials_df.columns.get_loc("Category") + 1

tv_commercials_df.insert(
    video_id_position,
    "Video ID",
    tv_commercials_df["URL"].map(unique_video_ids)
)

### List repeated videos

In [7]:
repeated_videos_df = (
    tv_commercials_df["Video ID"]
    .value_counts()
    .loc[lambda counts: counts > 1]
    .reset_index()
)

repeated_videos_df.columns = ["Video ID", "Occurrences"]

repeated_videos_df

      Video ID  Occurrences
0   video_0180           72
1   video_0460           64
2   video_0118           44
3   video_0233           12
4   video_0231            8
5   video_0229            6
6   video_0142            5
7   video_0172            5
8   video_0072            4
9   video_0109            4
10  video_0143            3
11  video_0293            3
12  video_0146            2
13  video_0149            2
14  video_0382            2

### Add commercial identifiers

In [8]:
commercial_id_position = tv_commercials_df.columns.get_loc("Category") + 1

tv_commercials_df.insert(
    commercial_id_position,
    "Commercial ID",
    (
            "tv_com_"
            + tv_commercials_df["Decade"].astype(str)
            + "_"
            + tv_commercials_df["Sequence"].astype(str)
    )
)

tv_commercials_df

,Decade,Sequence,Title,Category,Commercial ID,Video ID,URL,Start,End
0,1950,1,Norwich Liquid Peptans,"Health, Beauty & Personal Care",tv_com_1950_1,video_0001,https://youtu.be/G-zZFNf4PqQ,0:00:00,0:00:59
1,1950,2,Betty Crocker Cake,"Food, Beverages & Nutrition",tv_com_1950_2,video_0002,https://youtu.be/WMIMxj0PGGY,0:00:17,0:01:43
2,1950,3,Easy Clean Kentile Vinyl Asbestos Floor,"Household, Cleaning & Home Care",tv_com_1950_3,video_0003,https://youtu.be/O-baiygWMTQ,0:00:00,0:01:01
3,1950,4,Johnson's Floor Wax Polisher Scrubber,"Household, Cleaning & Home Care",tv_com_1950_4,video_0004,https://youtu.be/GGcZsStUjTg,0:00:00,0:01:31
4,1950,5,Best Foods Hellmann's Real Mayonnaise,"Food, Beverages & Nutrition",tv_com_1950_5,video_0005,https://youtu.be/bh6rDLrRcsc,0:00:00,0:01:01
...,...,...,...,...,...,...,...,...,...
955,2020,116,2025 Dell Technologies Holiday Help,"Technology, Communication & Eletronics",tv_com_2020_116,video_0735,https://youtu.be/ijGcSPZ4T8s,0:00:00,0:00:15
956,2020,117,2026 Chevrolet See the USA featuring Brooke Lee,"Personal, Public Transport & Travel",tv_com_2020_117,video_0736,https://youtu.be/g-6nRs4BqXQ,0:00:00,0:01:01
957,2020,118,2022 Southern Company Equitable Future,"Personal, Public Transport & Travel",tv_com_2020_118,video_0737,https://youtu.be/WybuYYSr3sw,0:00:00,0:01:01
958,2020,119,2023 Exxon Mobil Reduce Carbon Emissions,"Personal, Public Transport & Travel",tv_com_2020_119,video_0738,https://youtu.be/sYNhUg7mmnU,0:00:00,0:00:31
959,2020,120,2026 Delta Air Lines Olympics: What We Carry,"Personal, Public Transport & Travel",tv_com_2020_120,video_0739,https://youtu.be/WX1wgKCVJzc,0:00:00,0:00:30

### Save metadata as NDJSON

In [9]:
tv_commercials_df.to_json(
    "corpus/00_sources/tv_commercials.ndjson",
    orient="records",
    lines=True,
    force_ascii=False
)

### Import `tv_commercials.ndjson` into a pandas DataFrame

In [5]:
import pandas as pd

tv_commercials_df = pd.read_json(
    "corpus/00_sources/tv_commercials.ndjson",
    lines=True
)

### Document Download Outcomes for Source Videos

In [3]:
failed_downloads = {
    "video_0300": "Error: Unsupported URL: https://www.youtube.com/watch?v=_pHfv_HVSr&feature=youtu.be",
    "video_0739": "Error: [youtube] WX1wgKCVJzc: Private video.",
}

tv_commercials_df["Download Success"] = ~tv_commercials_df["Video ID"].isin(failed_downloads)

tv_commercials_df["Reason"] = (
    tv_commercials_df["Video ID"]
    .map(failed_downloads)
    .fillna("Success")
)

In [6]:
tv_commercials_df

,Decade,Sequence,Title,Category,Commercial ID,Video ID,URL,Start,End,Download Success,Reason
0,1950,1,Norwich Liquid Peptans,"Health, Beauty & Personal Care",tv_com_1950_1,video_0001,https://youtu.be/G-zZFNf4PqQ,0:00:00,0:00:59,True,Success
1,1950,2,Betty Crocker Cake,"Food, Beverages & Nutrition",tv_com_1950_2,video_0002,https://youtu.be/WMIMxj0PGGY,0:00:17,0:01:43,True,Success
2,1950,3,Easy Clean Kentile Vinyl Asbestos Floor,"Household, Cleaning & Home Care",tv_com_1950_3,video_0003,https://youtu.be/O-baiygWMTQ,0:00:00,0:01:01,True,Success
3,1950,4,Johnson's Floor Wax Polisher Scrubber,"Household, Cleaning & Home Care",tv_com_1950_4,video_0004,https://youtu.be/GGcZsStUjTg,0:00:00,0:01:31,True,Success
4,1950,5,Best Foods Hellmann's Real Mayonnaise,"Food, Beverages & Nutrition",tv_com_1950_5,video_0005,https://youtu.be/bh6rDLrRcsc,0:00:00,0:01:01,True,Success
...,...,...,...,...,...,...,...,...,...,...,...
955,2020,116,2025 Dell Technologies Holiday Help,"Technology, Communication & Eletronics",tv_com_2020_116,video_0735,https://youtu.be/ijGcSPZ4T8s,0:00:00,0:00:15,True,Success
956,2020,117,2026 Chevrolet See the USA featuring Brooke Lee,"Personal, Public Transport & Travel",tv_com_2020_117,video_0736,https://youtu.be/g-6nRs4BqXQ,0:00:00,0:01:01,True,Success
957,2020,118,2022 Southern Company Equitable Future,"Personal, Public Transport & Travel",tv_com_2020_118,video_0737,https://youtu.be/WybuYYSr3sw,0:00:00,0:01:01,True,Success
958,2020,119,2023 Exxon Mobil Reduce Carbon Emissions,"Personal, Public Transport & Travel",tv_com_2020_119,video_0738,https://youtu.be/sYNhUg7mmnU,0:00:00,0:00:31,True,Success
959,2020,120,2026 Delta Air Lines Olympics: What We Carry,"Personal, Public Transport & Travel",tv_com_2020_120,video_0739,https://youtu.be/WX1wgKCVJzc,0:00:00,0:00:30,False,Error: [youtube] WX1wgKCVJzc: Private video.

### Fix missing Start time in row 458

In [3]:
# Fix missing Start time in row 458
tv_commercials_df.loc[458, "Start"] = "0:00:00"

# Confirm the correction
tv_commercials_df.loc[458, ["Commercial ID", "Video ID", "Title", "Start", "End"]]

Commercial ID                   tv_com_1980_99
Video ID                            video_0311
Title            1980 Chef Boyardee Cannelloni
Start                                  0:00:00
End                                    0:00:35
Name: 458, dtype: str

### Fix invalid Start and End times in row 737

Error: 0:00:59 start time is after 0:00:30 end time

Correction: 0:00:00 start time and 0:00:59 end time

In [5]:
# Fix invalid Start time in row 737
tv_commercials_df.loc[737, "Start"] = "0:00:00"
tv_commercials_df.loc[737, "End"] = "0:00:59"

# Confirm the correction
tv_commercials_df.loc[737, ["Commercial ID", "Video ID", "Title", "Start", "End"]]

Commercial ID                 tv_com_2010_18
Video ID                          video_0580
Title            2010 IPhone4 Apple FaceTime
Start                                0:00:00
End                                  0:00:59
Name: 737, dtype: str

### Save metadata as NDJSON, Excel, and TSV

In [55]:
tv_commercials_df.to_json(
    "corpus/00_sources/tv_commercials.ndjson",
    orient="records",
    lines=True,
    force_ascii=False
)

tv_commercials_df.to_excel(
    "corpus/00_sources/tv_commercials.xlsx",
    index=False,
    engine="openpyxl"
)

tv_commercials_df.to_csv(
    "corpus/00_sources/tv_commercials.tsv",
    sep="\t",
    index=False
)

## Data Sampling

### Add transcript word counts

In [7]:
from pathlib import Path
import re
import pandas as pd

transcripts_dir = Path("corpus/04_transcripts")

def count_transcript_words(commercial_id):
    transcript_path = transcripts_dir / f"{commercial_id}.txt"

    if not transcript_path.exists():
        return pd.NA

    transcript_text = transcript_path.read_text(encoding="utf-8")
    return len(re.findall(r"\b\w+\b", transcript_text))

successful_downloads_mask = tv_commercials_df["Download Success"].eq(True)

tv_commercials_df["Transcript Word Count"] = pd.NA

tv_commercials_df.loc[successful_downloads_mask, "Transcript Word Count"] = (
    tv_commercials_df.loc[successful_downloads_mask, "Commercial ID"]
    .apply(count_transcript_words)
)

tv_commercials_df["Transcript Word Count"] = (
    tv_commercials_df["Transcript Word Count"]
    .astype("Int64")
)

tv_commercials_df[["Commercial ID", "Download Success", "Transcript Word Count"]]

       Commercial ID  Download Success  Transcript Word Count
0      tv_com_1950_1              True                    148
1      tv_com_1950_2              True                    248
2      tv_com_1950_3              True                    151
3      tv_com_1950_4              True                    245
4      tv_com_1950_5              True                    168
..               ...               ...                    ...
955  tv_com_2020_116              True                     40
956  tv_com_2020_117              True                    157
957  tv_com_2020_118              True                     88
958  tv_com_2020_119              True                     64
959  tv_com_2020_120             False                   <NA>

[960 rows x 3 columns]

### Descriptive statistics and outliers for 1950 transcript word counts

In [33]:
transcript_word_counts_1950_df = tv_commercials_df.loc[
    tv_commercials_df["Commercial ID"].str.contains(r"^tv_com_1950_", regex=True)
    & tv_commercials_df["Download Success"].eq(True),
    ["Commercial ID", "Title", "Transcript Word Count"]
].copy()

transcript_word_counts_1950 = transcript_word_counts_1950_df["Transcript Word Count"]

q1 = transcript_word_counts_1950.quantile(0.25)
q3 = transcript_word_counts_1950.quantile(0.75)
iqr = q3 - q1

lower_outlier_limit = q1 - 1.5 * iqr
upper_outlier_limit = q3 + 1.5 * iqr

transcript_word_count_outliers_1950 = transcript_word_counts_1950_df.loc[
    (transcript_word_counts_1950_df["Transcript Word Count"] < lower_outlier_limit)
    | (transcript_word_counts_1950_df["Transcript Word Count"] > upper_outlier_limit)
    ].sort_values("Transcript Word Count")

transcript_word_counts_1950.describe()

count         120.0
mean     159.691667
std       46.495287
min            28.0
25%           133.5
50%           155.0
75%           176.5
max           312.0
Name: Transcript Word Count, dtype: Float64

In [34]:
display(transcript_word_count_outliers_1950)

,Commercial ID,Title,Transcript Word Count
99,tv_com_1950_100,Volkswagen Beetle,28
118,tv_com_1950_119,Univac computer,60
3,tv_com_1950_4,Johnson's Floor Wax Polisher Scrubber,245
1,tv_com_1950_2,Betty Crocker Cake,248
79,tv_com_1950_80,Ford Two Ford Families I was practically a pri...,265
87,tv_com_1950_88,1959 Chevy's with Roy Rogers,269
26,tv_com_1950_27,Tide Detergent,290
97,tv_com_1950_98,1955 Rambler Cross Country Wagon Car,308
36,tv_com_1950_37,Kellogg's Special K Cereal,312

### Descriptive statistics and outliers for 1960 transcript word counts

In [35]:
transcript_word_counts_1960_df = tv_commercials_df.loc[
    tv_commercials_df["Commercial ID"].str.contains(r"^tv_com_1960_", regex=True)
    & tv_commercials_df["Download Success"].eq(True),
    ["Commercial ID", "Title", "Transcript Word Count"]
].copy()

transcript_word_counts_1960 = transcript_word_counts_1960_df["Transcript Word Count"]

q1 = transcript_word_counts_1960.quantile(0.25)
q3 = transcript_word_counts_1960.quantile(0.75)
iqr = q3 - q1

lower_outlier_limit = q1 - 1.5 * iqr
upper_outlier_limit = q3 + 1.5 * iqr

transcript_word_count_outliers_1960 = transcript_word_counts_1960_df.loc[
    (transcript_word_counts_1960_df["Transcript Word Count"] < lower_outlier_limit)
    | (transcript_word_counts_1960_df["Transcript Word Count"] > upper_outlier_limit)
    ].sort_values("Transcript Word Count")

transcript_word_counts_1960.describe()

count         120.0
mean     109.366667
std        44.66193
min            22.0
25%            69.0
50%           108.0
75%           142.0
max           285.0
Name: Transcript Word Count, dtype: Float64

In [36]:
display(transcript_word_count_outliers_1960)

      Commercial ID                    Title  Transcript Word Count
134  tv_com_1960_15  Timex Watches self-wind                    285

### Descriptive statistics and outliers for 1970 transcript word counts

In [37]:
transcript_word_counts_1970_df = tv_commercials_df.loc[
    tv_commercials_df["Commercial ID"].str.contains(r"^tv_com_1970_", regex=True)
    & tv_commercials_df["Download Success"].eq(True),
    ["Commercial ID", "Title", "Transcript Word Count"]
].copy()

transcript_word_counts_1970 = transcript_word_counts_1970_df["Transcript Word Count"]

q1 = transcript_word_counts_1970.quantile(0.25)
q3 = transcript_word_counts_1970.quantile(0.75)
iqr = q3 - q1

lower_outlier_limit = q1 - 1.5 * iqr
upper_outlier_limit = q3 + 1.5 * iqr

transcript_word_count_outliers_1970 = transcript_word_counts_1970_df.loc[
    (transcript_word_counts_1970_df["Transcript Word Count"] < lower_outlier_limit)
    | (transcript_word_counts_1970_df["Transcript Word Count"] > upper_outlier_limit)
    ].sort_values("Transcript Word Count")

transcript_word_counts_1970.describe()

count        120.0
mean        81.975
std      34.575569
min            2.0
25%           63.0
50%           73.5
75%          90.25
max          185.0
Name: Transcript Word Count, dtype: Float64

In [38]:
display(transcript_word_count_outliers_1970)

,Commercial ID,Title,Transcript Word Count
300,tv_com_1970_61,Coca-Cola plenty of coke on hand,2
328,tv_com_1970_89,Volvo 1971,6
330,tv_com_1970_91,Chevy Monza See what's new 1978,19
346,tv_com_1970_107,Superscope Stereo,138
268,tv_com_1970_29,Niagara Adjustable Bed,141
344,tv_com_1970_105,Big Wally wall cleaning foaming-spray,142
345,tv_com_1970_106,Ajax All-Purpose Cleaner Armed with Ajax 1979,148
240,tv_com_1970_1,Coal Exxon,149
351,tv_com_1970_112,1974 RCA TVs 50th Anniversary,149
340,tv_com_1970_101,Dawn Dishwashing Liquid Detergent early '70s,151
350,tv_com_1970_111,1971 Kodak Christmas Movie Camera featuring Jo...,153
341,tv_com_1970_102,Hefty Scrap Bags and Trash Can Liners 1970,158
321,tv_com_1970_82,Lemon Fresh Joy dishwashing liquid 1973,161
342,tv_com_1970_103,Sears Snow Tires 1973,174
339,tv_com_1970_100,All-Tempa Cheer Detergent,175
279,tv_com_1970_40,Texaco Institutional,184
349,tv_com_1970_110,1973 RCA TV Chief Engineers,185

### Descriptive statistics and outliers for 1980 transcript word counts

In [39]:
transcript_word_counts_1980_df = tv_commercials_df.loc[
    tv_commercials_df["Commercial ID"].str.contains(r"^tv_com_1980_", regex=True)
    & tv_commercials_df["Download Success"].eq(True),
    ["Commercial ID", "Title", "Transcript Word Count"]
].copy()

transcript_word_counts_1980 = transcript_word_counts_1980_df["Transcript Word Count"]

q1 = transcript_word_counts_1980.quantile(0.25)
q3 = transcript_word_counts_1980.quantile(0.75)
iqr = q3 - q1

lower_outlier_limit = q1 - 1.5 * iqr
upper_outlier_limit = q3 + 1.5 * iqr

transcript_word_count_outliers_1980 = transcript_word_counts_1980_df.loc[
    (transcript_word_counts_1980_df["Transcript Word Count"] < lower_outlier_limit)
    | (transcript_word_counts_1980_df["Transcript Word Count"] > upper_outlier_limit)
    ].sort_values("Transcript Word Count")

transcript_word_counts_1980.describe()

count        119.0
mean          72.0
std      35.054921
min            2.0
25%           55.5
50%           72.0
75%           85.0
max          211.0
Name: Transcript Word Count, dtype: Float64

In [40]:
display(transcript_word_count_outliers_1980)

,Commercial ID,Title,Transcript Word Count
478,tv_com_1980_119,1986 Benetton Clothing,2
401,tv_com_1980_42,1984 Chevrolet S10 Blazer Chevy tough and taki...,4
421,tv_com_1980_62,"1985 GE General Electric Stereo ""The power of ...",4
396,tv_com_1980_37,1984 Jordache Jeans,8
476,tv_com_1980_117,Jordache Jeans,8
406,tv_com_1980_47,1980 Greyhound Bus,131
479,tv_com_1980_120,1980 Calvin Klein Jeans featuring Brooke Shields,136
379,tv_com_1980_20,1981 Lysol Scent II Character Actors,141
416,tv_com_1980_57,1983 Next Wave Corolla,144
419,tv_com_1980_60,1983 IBM Personal Computer sofware Charlie Cha...,147
420,tv_com_1980_61,1981 RCA Colortrax 2000 television set with ad...,153
380,tv_com_1980_21,1980 Windex,161
428,tv_com_1980_69,1988 Magnavox Escort Camcorder,196
442,tv_com_1980_83,1983 Time Magazine Get a free push button phone,211

### Descriptive statistics and outliers for 1990 transcript word counts

In [41]:
transcript_word_counts_1990_df = tv_commercials_df.loc[
    tv_commercials_df["Commercial ID"].str.contains(r"^tv_com_1990_", regex=True)
    & tv_commercials_df["Download Success"].eq(True),
    ["Commercial ID", "Title", "Transcript Word Count"]
].copy()

transcript_word_counts_1990 = transcript_word_counts_1990_df["Transcript Word Count"]

q1 = transcript_word_counts_1990.quantile(0.25)
q3 = transcript_word_counts_1990.quantile(0.75)
iqr = q3 - q1

lower_outlier_limit = q1 - 1.5 * iqr
upper_outlier_limit = q3 + 1.5 * iqr

transcript_word_count_outliers_1990 = transcript_word_counts_1990_df.loc[
    (transcript_word_counts_1990_df["Transcript Word Count"] < lower_outlier_limit)
    | (transcript_word_counts_1990_df["Transcript Word Count"] > upper_outlier_limit)
    ].sort_values("Transcript Word Count")

transcript_word_counts_1990.describe()

count        120.0
mean     66.683333
std      41.412048
min            0.0
25%          39.75
50%           59.5
75%          83.25
max          242.0
Name: Transcript Word Count, dtype: Float64

In [42]:
display(transcript_word_count_outliers_1990)

,Commercial ID,Title,Transcript Word Count
573,tv_com_1990_94,1991 AT & T Service,150
508,tv_com_1990_29,1994 Merry-Go-Round Clothing Pizza Delivery,183
512,tv_com_1990_33,1993 Dental White,202
520,tv_com_1990_41,1996 Nordic Track Walk,207
545,tv_com_1990_66,1996 Sprint's telephone service Dime Lady Cand...,242

### Descriptive statistics and outliers for 2000 transcript word counts

In [43]:
transcript_word_counts_2000_df = tv_commercials_df.loc[
    tv_commercials_df["Commercial ID"].str.contains(r"^tv_com_2000_", regex=True)
    & tv_commercials_df["Download Success"].eq(True),
    ["Commercial ID", "Title", "Transcript Word Count"]
].copy()

transcript_word_counts_2000 = transcript_word_counts_2000_df["Transcript Word Count"]

q1 = transcript_word_counts_2000.quantile(0.25)
q3 = transcript_word_counts_2000.quantile(0.75)
iqr = q3 - q1

lower_outlier_limit = q1 - 1.5 * iqr
upper_outlier_limit = q3 + 1.5 * iqr

transcript_word_count_outliers_2000 = transcript_word_counts_2000_df.loc[
    (transcript_word_counts_2000_df["Transcript Word Count"] < lower_outlier_limit)
    | (transcript_word_counts_2000_df["Transcript Word Count"] > upper_outlier_limit)
    ].sort_values("Transcript Word Count")

transcript_word_counts_2000.describe()

count        120.0
mean     67.516667
std      46.150645
min            4.0
25%           36.0
50%           57.5
75%           91.5
max          246.0
Name: Transcript Word Count, dtype: Float64

In [44]:
display(transcript_word_count_outliers_2000)

,Commercial ID,Title,Transcript Word Count
672,tv_com_2000_73,2000 Lysol Desinfectant Spray,180
643,tv_com_2000_44,2001 Apple iDVD,197
637,tv_com_2000_38,2003 Total Gym Equipment featuring Chuck Norri...,214
677,tv_com_2000_78,2000 OxiClean featuring Billy Mays,216
682,tv_com_2000_83,2005 Ortho Evra The Pill Contraceptive Patch,224
652,tv_com_2000_53,2005 T-Mobile Families Talk Free featuring Cat...,246

### Descriptive statistics and outliers for 2010 transcript word counts

In [45]:
transcript_word_counts_2010_df = tv_commercials_df.loc[
    tv_commercials_df["Commercial ID"].str.contains(r"^tv_com_2010_", regex=True)
    & tv_commercials_df["Download Success"].eq(True),
    ["Commercial ID", "Title", "Transcript Word Count"]
].copy()

transcript_word_counts_2010 = transcript_word_counts_2010_df["Transcript Word Count"]

q1 = transcript_word_counts_2010.quantile(0.25)
q3 = transcript_word_counts_2010.quantile(0.75)
iqr = q3 - q1

lower_outlier_limit = q1 - 1.5 * iqr
upper_outlier_limit = q3 + 1.5 * iqr

transcript_word_count_outliers_2010 = transcript_word_counts_2010_df.loc[
    (transcript_word_counts_2010_df["Transcript Word Count"] < lower_outlier_limit)
    | (transcript_word_counts_2010_df["Transcript Word Count"] > upper_outlier_limit)
    ].sort_values("Transcript Word Count")

transcript_word_counts_2010.describe()

count        120.0
mean     74.216667
std      47.536308
min            0.0
25%          48.75
50%           64.0
75%           89.0
max          277.0
Name: Transcript Word Count, dtype: Float64

In [46]:
display(transcript_word_count_outliers_2010)

,Commercial ID,Title,Transcript Word Count
805,tv_com_2010_86,2014 Cadillac ELR Poolside,164
820,tv_com_2010_101,2019 Otezla Psoriasis Little Things Pool and F...,167
720,tv_com_2010_1,2016 Snapple Peach Tea Make time for Snapple,178
740,tv_com_2010_21,2012 Axe Deodorant Use in moderation Meet the ...,210
752,tv_com_2010_33,2010 Lipitor Medication,212
747,tv_com_2010_28,2018 LG Mobile V30 Never Compromise: Lease,247
786,tv_com_2010_67,2014 Samsung Mobile Milk Music Put Your Spin O...,250
753,tv_com_2010_34,2018 Sprint Unlimited for Freedom,277

### Descriptive statistics and outliers for 2020 transcript word counts

In [47]:
transcript_word_counts_2020_df = tv_commercials_df.loc[
    tv_commercials_df["Commercial ID"].str.contains(r"^tv_com_2020_", regex=True)
    & tv_commercials_df["Download Success"].eq(True),
    ["Commercial ID", "Title", "Transcript Word Count"]
].copy()

transcript_word_counts_2020 = transcript_word_counts_2020_df["Transcript Word Count"]

q1 = transcript_word_counts_2020.quantile(0.25)
q3 = transcript_word_counts_2020.quantile(0.75)
iqr = q3 - q1

lower_outlier_limit = q1 - 1.5 * iqr
upper_outlier_limit = q3 + 1.5 * iqr

transcript_word_count_outliers_2020 = transcript_word_counts_2020_df.loc[
    (transcript_word_counts_2020_df["Transcript Word Count"] < lower_outlier_limit)
    | (transcript_word_counts_2020_df["Transcript Word Count"] > upper_outlier_limit)
    ].sort_values("Transcript Word Count")

transcript_word_counts_2020.describe()

count        119.0
mean     56.588235
std      37.680056
min            0.0
25%           30.0
50%           46.0
75%           77.5
max          252.0
Name: Transcript Word Count, dtype: Float64

In [48]:
display(transcript_word_count_outliers_2020)

,Commercial ID,Title,Transcript Word Count
956,tv_com_2020_117,2026 Chevrolet See the USA featuring Brooke Lee,157
950,tv_com_2020_111,2025 Delta Air Lines Olympics: Arrivals featur...,159
944,tv_com_2020_105,2026 Amazon Alexa+ Super Bowl Chris Hemsworth ...,173
939,tv_com_2020_100,2026 Handy Heater Turbo Heat 360 Stay Warm: $2...,252

### Initialise outlier flag column

In [17]:
tv_commercials_df["Outlier"] = False

tv_commercials_df[["Commercial ID", "Transcript Word Count", "Outlier"]]

       Commercial ID  Transcript Word Count  Outlier
0      tv_com_1950_1                    148    False
1      tv_com_1950_2                    248    False
2      tv_com_1950_3                    151    False
3      tv_com_1950_4                    245    False
4      tv_com_1950_5                    168    False
..               ...                    ...      ...
955  tv_com_2020_116                     40    False
956  tv_com_2020_117                    157    False
957  tv_com_2020_118                     88    False
958  tv_com_2020_119                     64    False
959  tv_com_2020_120                   <NA>    False

[960 rows x 3 columns]

### Mark transcript word count outliers

In [49]:
outlier_commercial_ids = pd.concat(
    [
        transcript_word_count_outliers_1950["Commercial ID"],
        transcript_word_count_outliers_1960["Commercial ID"],
        transcript_word_count_outliers_1970["Commercial ID"],
        transcript_word_count_outliers_1980["Commercial ID"],
        transcript_word_count_outliers_1990["Commercial ID"],
        transcript_word_count_outliers_2000["Commercial ID"],
        transcript_word_count_outliers_2010["Commercial ID"],
        transcript_word_count_outliers_2020["Commercial ID"],
    ],
    ignore_index=True
)

tv_commercials_df["Outlier"] = tv_commercials_df["Commercial ID"].isin(outlier_commercial_ids)

tv_commercials_df.loc[
    tv_commercials_df["Outlier"],
    ["Commercial ID", "Title", "Transcript Word Count", "Outlier"]
]

,Commercial ID,Title,Transcript Word Count,Outlier
1,tv_com_1950_2,Betty Crocker Cake,248,True
3,tv_com_1950_4,Johnson's Floor Wax Polisher Scrubber,245,True
26,tv_com_1950_27,Tide Detergent,290,True
36,tv_com_1950_37,Kellogg's Special K Cereal,312,True
79,tv_com_1950_80,Ford Two Ford Families I was practically a pri...,265,True
...,...,...,...,...
820,tv_com_2010_101,2019 Otezla Psoriasis Little Things Pool and F...,167,True
939,tv_com_2020_100,2026 Handy Heater Turbo Heat 360 Stay Warm: $2...,252,True
944,tv_com_2020_105,2026 Amazon Alexa+ Super Bowl Chris Hemsworth ...,173,True
950,tv_com_2020_111,2025 Delta Air Lines Olympics: Arrivals featur...,159,True
956,tv_com_2020_117,2026 Chevrolet See the USA featuring Brooke Lee,157,True

### Count non-outlier commercials by decade

In [51]:
non_outlier_commercials_by_decade = (
    tv_commercials_df.loc[
        tv_commercials_df["Download Success"].eq(True)
        & tv_commercials_df["Outlier"].eq(False)
        ]
    .assign(
        Decade=tv_commercials_df["Commercial ID"].str.extract(r"^tv_com_(\d{4})_")[0]
    )
    .groupby("Decade")
    .size()
    .reset_index(name="Non-Outlier Commercials")
)

non_outlier_commercials_by_decade

  Decade  Non-Outlier Commercials
0   1950                      111
1   1960                      119
2   1970                      103
3   1980                      105
4   1990                      115
5   2000                      114
6   2010                      112
7   2020                      115

#### Show the decade with the minimum

In [52]:
non_outlier_commercials_by_decade.loc[
    non_outlier_commercials_by_decade["Non-Outlier Commercials"]
    .eq(non_outlier_commercials_by_decade["Non-Outlier Commercials"].min())
]

  Decade  Non-Outlier Commercials
2   1970                      103

### Count non-outlier commercials, longer than 10 words, by decade

In [5]:
tv_commercials_df["10 Words or Fewer"] = (
    tv_commercials_df["Transcript Word Count"].le(10)
)

       Commercial ID  Transcript Word Count  10 Words or Fewer
0      tv_com_1950_1                  148.0              False
1      tv_com_1950_2                  248.0              False
2      tv_com_1950_3                  151.0              False
3      tv_com_1950_4                  245.0              False
4      tv_com_1950_5                  168.0              False
..               ...                    ...                ...
955  tv_com_2020_116                   40.0              False
956  tv_com_2020_117                  157.0              False
957  tv_com_2020_118                   88.0              False
958  tv_com_2020_119                   64.0              False
959  tv_com_2020_120                    NaN              False

[960 rows x 3 columns]

In [6]:
non_outlier_longer_than_10_by_decade = (
    tv_commercials_df.loc[
        tv_commercials_df["Download Success"].eq(True)
        & tv_commercials_df["Outlier"].eq(False)
        & tv_commercials_df["10 Words or Fewer"].eq(False)
        ]
    .groupby("Decade")
    .size()
    .reset_index(name="Non-Outlier Commercials Longer Than 10 Words")
)

non_outlier_longer_than_10_by_decade

   Decade  Non-Outlier Commercials Longer Than 10 Words
0    1950                                           111
1    1960                                           119
2    1970                                           103
3    1980                                           105
4    1990                                           112
5    2000                                           110
6    2010                                           107
7    2020                                           113

#### Show the decade with the minimum

In [7]:
non_outlier_longer_than_10_by_decade.loc[
    non_outlier_longer_than_10_by_decade["Non-Outlier Commercials Longer Than 10 Words"]
    .eq(non_outlier_longer_than_10_by_decade["Non-Outlier Commercials Longer Than 10 Words"].min())
]

   Decade  Non-Outlier Commercials Longer Than 10 Words
2    1970                                           103

### Count non-outlier commercials, longer than 20 words, by decade

In [8]:
tv_commercials_df["20 Words or Fewer"] = (
    tv_commercials_df["Transcript Word Count"].le(20)
)

In [9]:
non_outlier_longer_than_20_by_decade = (
    tv_commercials_df.loc[
        tv_commercials_df["Download Success"].eq(True)
        & tv_commercials_df["Outlier"].eq(False)
        & tv_commercials_df["20 Words or Fewer"].eq(False)
        ]
    .groupby("Decade")
    .size()
    .reset_index(name="Non-Outlier Commercials Longer Than 20 Words")
)

non_outlier_longer_than_20_by_decade

   Decade  Non-Outlier Commercials Longer Than 20 Words
0    1950                                           111
1    1960                                           119
2    1970                                           103
3    1980                                           103
4    1990                                           110
5    2000                                           106
6    2010                                           104
7    2020                                           103

#### Show the decade with the minimum

In [10]:
non_outlier_longer_than_20_by_decade.loc[
    non_outlier_longer_than_20_by_decade["Non-Outlier Commercials Longer Than 20 Words"]
    .eq(non_outlier_longer_than_20_by_decade["Non-Outlier Commercials Longer Than 20 Words"].min())
]

   Decade  Non-Outlier Commercials Longer Than 20 Words
2    1970                                           103
3    1980                                           103
7    2020                                           103

### Randomly select balanced non-outlier sample by decade

Given that the minimum number of non-outlier commercials, longer than 20 words, is 103, I'd like to randomly select 103 commercials from each decade. What is the best way to do this? I was thinking of creating a `Selected` column to indicate which commercials were selected...

Yes — creating a `Selected` column is a good approach because it keeps the sampling decision inside `tv_commercials_df`, makes the sample easy to inspect, and lets you save/export it with the rest of the metadata.

I would recommend:

1. Initialise `Selected` as `False`.
2. Filter to eligible commercials:
   - `Download Success == True`
   - `Outlier == False`
   - `Transcript Word Count > 20`
3. Infer decade from `Commercial ID`.
4. Randomly sample `103` rows per decade.
5. Mark those rows as `Selected == True`.
6. Use a fixed `random_state` so the selection is reproducible.

In [12]:
sample_size_per_decade = 103
random_seed = 42

tv_commercials_df["Selected"] = False

eligible_commercials_df = (
    tv_commercials_df.loc[
        tv_commercials_df["Download Success"].eq(True)
        & tv_commercials_df["Outlier"].eq(False)
        & tv_commercials_df["Transcript Word Count"].gt(20)
        ]
    .assign(
        Decade_From_ID=lambda df: df["Commercial ID"].str.extract(r"^tv_com_(\d{4})_")[0]
    )
)

selected_commercial_indices = (
    eligible_commercials_df
    .groupby("Decade_From_ID", group_keys=False)
    .sample(n=sample_size_per_decade, random_state=random_seed)
    .index
)

tv_commercials_df.loc[selected_commercial_indices, "Selected"] = True

selected_commercials_by_decade = (
    tv_commercials_df.loc[tv_commercials_df["Selected"]]
    .assign(
        Decade_From_ID=lambda df: df["Commercial ID"].str.extract(r"^tv_com_(\d{4})_")[0]
    )
    .groupby("Decade_From_ID")
    .size()
    .reset_index(name="Selected Commercials")
)

selected_commercials_by_decade

  Decade_From_ID  Selected Commercials
0           1950                   103
1           1960                   103
2           1970                   103
3           1980                   103
4           1990                   103
5           2000                   103
6           2010                   103
7           2020                   103

In [13]:
tv_commercials_df

,Decade,Sequence,Title,Category,Commercial ID,Video ID,URL,Start,End,Download Success,Reason,Transcript Word Count,Outlier,10 Words or Fewer,20 Words or Fewer,Selected
0,1950,1,Norwich Liquid Peptans,"Health, Beauty & Personal Care",tv_com_1950_1,video_0001,https://youtu.be/G-zZFNf4PqQ,0:00:00,0:00:59,True,Success,148.0,False,False,False,True
1,1950,2,Betty Crocker Cake,"Food, Beverages & Nutrition",tv_com_1950_2,video_0002,https://youtu.be/WMIMxj0PGGY,0:00:17,0:01:43,True,Success,248.0,True,False,False,False
2,1950,3,Easy Clean Kentile Vinyl Asbestos Floor,"Household, Cleaning & Home Care",tv_com_1950_3,video_0003,https://youtu.be/O-baiygWMTQ,0:00:00,0:01:01,True,Success,151.0,False,False,False,True
3,1950,4,Johnson's Floor Wax Polisher Scrubber,"Household, Cleaning & Home Care",tv_com_1950_4,video_0004,https://youtu.be/GGcZsStUjTg,0:00:00,0:01:31,True,Success,245.0,True,False,False,False
4,1950,5,Best Foods Hellmann's Real Mayonnaise,"Food, Beverages & Nutrition",tv_com_1950_5,video_0005,https://youtu.be/bh6rDLrRcsc,0:00:00,0:01:01,True,Success,168.0,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,2020,116,2025 Dell Technologies Holiday Help,"Technology, Communication & Electronics",tv_com_2020_116,video_0735,https://youtu.be/ijGcSPZ4T8s,0:00:00,0:00:15,True,Success,40.0,False,False,False,True
956,2020,117,2026 Chevrolet See the USA featuring Brooke Lee,"Personal, Public Transport & Travel",tv_com_2020_117,video_0736,https://youtu.be/g-6nRs4BqXQ,0:00:00,0:01:01,True,Success,157.0,True,False,False,False
957,2020,118,2022 Southern Company Equitable Future,"Personal, Public Transport & Travel",tv_com_2020_118,video_0737,https://youtu.be/WybuYYSr3sw,0:00:00,0:01:01,True,Success,88.0,False,False,False,True
958,2020,119,2023 Exxon Mobil Reduce Carbon Emissions,"Personal, Public Transport & Travel",tv_com_2020_119,video_0738,https://youtu.be/sYNhUg7mmnU,0:00:00,0:00:31,True,Success,64.0,False,False,False,True
959,2020,120,2026 Delta Air Lines Olympics: What We Carry,"Personal, Public Transport & Travel",tv_com_2020_120,video_0739,https://youtu.be/WX1wgKCVJzc,0:00:00,0:00:30,False,Error: [youtube] WX1wgKCVJzc: Private video.,NaN,False,False,False,False

### Save metadata as NDJSON, Excel, and TSV

In [14]:
tv_commercials_df.to_json(
    "corpus/00_sources/tv_commercials.ndjson",
    orient="records",
    lines=True,
    force_ascii=False
)

tv_commercials_df.to_excel(
    "corpus/00_sources/tv_commercials.xlsx",
    index=False,
    engine="openpyxl"
)

tv_commercials_df.to_csv(
    "corpus/00_sources/tv_commercials.tsv",
    sep="\t",
    index=False
)

## Standardise `Category` labels

### Import `tv_commercials.ndjson` into a pandas DataFrame

In [1]:
import pandas as pd

tv_commercials_df = pd.read_json(
    "corpus/00_sources/tv_commercials.ndjson",
    lines=True
)

### Inspect the `Category` column

In [13]:
set(tv_commercials_df["Category"].dropna())

{'Food, Beverage & Nutrition',
 'Food, Beverages & Nutrition',
 'Health, Beauty & Personal Care',
 'Household, Cleaning & Home Care',
 'Personal, Public Transport & Travel',
 'Personal, Public Transport & Travel & Energy',
 'Retail (Fashion/ Consumer Goods) &  Services',
 'Retail (Fashion/ Consumer Goods) &  Services ',
 'Retail (Fashion/ Consumer Goods) &  Services, Consumer Goods & Services',
 'Retail (Fashion/ Consumer Goods) &  Services, Fashion & Consumer Goods',
 'Technology, Communication & Electronics',
 'Technology, Communication & Eletronics',
 'Transport (Personal/ Public), Travel & Energy'}

### Apply corrections to `Category` labels

In [14]:
category_replacements = {
    "Food, Beverage & Nutrition": "Food, Beverages & Nutrition",
    "Retail (Fashion/ Consumer Goods) &  Services": "Retail (Fashion & Consumer Goods) & Services",
    "Retail (Fashion/ Consumer Goods) &  Services ": "Retail (Fashion & Consumer Goods) & Services",
    "Retail (Fashion/ Consumer Goods) &  Services, Consumer Goods & Services": "Retail (Fashion & Consumer Goods) & Services, Consumer Goods & Services",
    "Retail (Fashion/ Consumer Goods) &  Services, Fashion & Consumer Goods": "Retail (Fashion & Consumer Goods) & Services, Fashion & Consumer Goods",
    "Technology, Communication & Eletronics": "Technology, Communication & Electronics",
    "Transport (Personal/ Public), Travel & Energy": "Transport (Personal & Public), Travel & Energy",
}

tv_commercials_df["Category"] = tv_commercials_df["Category"].replace(category_replacements)

set(tv_commercials_df["Category"].dropna())

{'Food, Beverages & Nutrition',
 'Health, Beauty & Personal Care',
 'Household, Cleaning & Home Care',
 'Personal, Public Transport & Travel',
 'Personal, Public Transport & Travel & Energy',
 'Retail (Fashion & Consumer Goods) & Services',
 'Retail (Fashion & Consumer Goods) & Services, Consumer Goods & Services',
 'Retail (Fashion & Consumer Goods) & Services, Fashion & Consumer Goods',
 'Technology, Communication & Electronics',
 'Transport (Personal & Public), Travel & Energy'}

### Save metadata as NDJSON, Excel, and TSV

In [15]:
tv_commercials_df.to_json(
    "corpus/00_sources/tv_commercials.ndjson",
    orient="records",
    lines=True,
    force_ascii=False
)

tv_commercials_df.to_excel(
    "corpus/00_sources/tv_commercials.xlsx",
    index=False,
    engine="openpyxl"
)

tv_commercials_df.to_csv(
    "corpus/00_sources/tv_commercials.tsv",
    sep="\t",
    index=False
)

### Import `tv_commercials.ndjson` into a pandas DataFrame

In [1]:
import pandas as pd

tv_commercials_df = pd.read_json(
    "corpus/00_sources/tv_commercials.ndjson",
    lines=True
)

### Create selected commercials subset

Slice the full metadata DataFrame to retain only the selected commercials and keep the `Decade`, `Category`, and `Commercial ID` columns for inspection or export.

In [2]:
tv_commercials_selected_1_df = tv_commercials_df.loc[
    tv_commercials_df["Selected"].eq(True),
    ["Decade", "Category", "Commercial ID"]
].copy()

tv_commercials_selected_1_df

     Decade                                 Category    Commercial ID
0      1950           Health, Beauty & Personal Care    tv_com_1950_1
2      1950          Household, Cleaning & Home Care    tv_com_1950_3
4      1950              Food, Beverages & Nutrition    tv_com_1950_5
5      1950              Food, Beverages & Nutrition    tv_com_1950_6
6      1950              Food, Beverages & Nutrition    tv_com_1950_7
..      ...                                      ...              ...
953    2020  Technology, Communication & Electronics  tv_com_2020_114
954    2020  Technology, Communication & Electronics  tv_com_2020_115
955    2020  Technology, Communication & Electronics  tv_com_2020_116
957    2020      Personal, Public Transport & Travel  tv_com_2020_118
958    2020      Personal, Public Transport & Travel  tv_com_2020_119

[824 rows x 3 columns]

### Save selected commercials metadata as NDJSON, Excel, and TSV

In [3]:
tv_commercials_selected_1_df.to_json(
    "corpus/00_sources/tv_commercials_selected_1.ndjson",
    orient="records",
    lines=True,
    force_ascii=False
)

tv_commercials_selected_1_df.to_excel(
    "corpus/00_sources/tv_commercials_selected_1.xlsx",
    index=False,
    engine="openpyxl"
)

tv_commercials_selected_1_df.to_csv(
    "corpus/00_sources/tv_commercials_selected_1.tsv",
    sep="\t",
    index=False
)